nav = [
  { "Agenda" = [
    "agenda.md",
    "agenda/2026-01-06-p-um.md",
    "agenda/2026-01-06-p-um/remerciements.md",
  ] },
  { "Annuaire" = [
    "annuaire.md",
    "annuaire/lessimonescoopfr.md",
  ] },
  { "Arts plastiques" = [
    "arts-plastiques.md",
  ] },
  { "Association" = [
    "association.md",
    { "Conseils des voisins" = [
      "association/conseils-des-voisins.md",
      "association/conseils-des-voisins/conseildesgv25.md",
      "association/conseils-des-voisins/conseildesgv25/cr.md",
      "association/conseils-des-voisins/conseildesgv25/rapport-moral-2025.md",
      "association/conseils-des-voisins/conseildesgv26.md",
      "association/conseils-des-voisins/conseildesgv26/invitation.md",
      "association/conseils-des-voisins/conseildesgv26/pj.md",
      "association/conseils-des-voisins/conseildesgv26/support.md",
    ] },
    "association/historique.md",
    "association/manifeste.md",
  ] },
  { "Blog" = [
    "blog.md",
  ] },
  { "Civisme" = [
    "civisme.md",
    "civisme/empathie.md",
    "civisme/empathie/2025.md",
    "civisme/profession-empathie-nationale.md",
    "civisme/social.md",
  ] },
  { "Dons" = [
    "dons.md",
  ] },
  { "Numérique" = [
    "numerique.md",
    "numerique/comptes.md",
    "numerique/creatif.md",
    "numerique/interdependance.md",
    "numerique/mecenat.md",
    "numerique/parislenuage.md",
    "numerique/recyclage.md",
    "numerique/serveurs.md",
    "numerique/serveurs/max.md",
    { "Services" = [
      "numerique/services.md",
      "numerique/services/alpha.md",
      "numerique/services/anciens.md",
      "numerique/services/annuaire.md",
      "numerique/services/backlog.md",
      "numerique/services/beta.md",
      "numerique/services/calendrier.md",
      "numerique/services/changelog.md",
      "numerique/services/decap.md",
      "numerique/services/email.md",
      "numerique/services/forgejo.md",
      "numerique/services/ghostio.md",
      "numerique/services/hedgedoc.md",
      "numerique/services/homarr.md",
      "numerique/services/jitsi.md",
      "numerique/services/jswiki.md",
      "numerique/services/keepass.md",
      "numerique/services/keycloak.md",
      "numerique/services/linkding.md",
      "numerique/services/sftpgo.md",
      "numerique/services/vikunja.md",
      "numerique/services/wagtail.md",
    ] },
    { "Sociabilité numérique" = [
      "numerique/sociabilite-numerique.md",
      "numerique/sociabilite-numerique/amenagement.md",
      "numerique/sociabilite-numerique/amenagement/centres.md",
      "numerique/sociabilite-numerique/amenagement/partage-wifi.md",
      "numerique/sociabilite-numerique/presentation.md",
    ] },
    "numerique/sujets.md",
    "numerique/sujets/assistance.md",
    "numerique/sujets/secrets.md",
  ] },
]